version: "3.9"
services:
  db:
    image: postgres:14.2
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  db-test:
    image: postgres:14.2
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5431:5432"
